### ISSUE TITLE
Updated to latest and now plugin disabled

### ISSUE THREAD

**Issue by spotd** [rkingon/Craft-Plugin--Redirect-Manager#15]
I also cant enable the plugin in settings? v 1.9.1
No errors in devmode

**Comment by rkingon** [comment]
can you try downloading a fresh zip & completely removing the previous?

I changed the casing on the plugin file at one point and GIT does a terrible job with casing

**Comment by spotd** [comment]
Ok deleted existing, downloaded and uploaded... Same problem

**Comment by rkingon** [comment]
Class field in your db is likely pointing to the old, I should prob write a migrate file.

execute this in your sql: `UPDATE craft_plugins SET class="RedirectManager" WHERE class="Redirectmanager"`

via sequalpro, phpmyadmin, cli, ect...

**Comment by spotd** [comment]
That worked a treat, thank you
