### ISSUE TITLE
no way to redirect queries to another web page

### ISSUE THREAD

**Issue by richardkwc** [rkingon/Craft-Plugin--Redirect-Manager#9]
I'm attempting to redirect:
www.website.com/?post_type=testimonials
To:
www.website.com/about-us

I've tried the following regex rules with no success:
#^\?post_type=testimonials#
#^\?post_type=testimonials$#
#post_type=testimonials$#

All of them just stay on the homepage with the query appended when accessing the target url.

**Comment by mattweldon** [comment]
I could also do with the ability to redirect based on querystring.

@rkingon have you had any thoughts on this? If not, I might take a look at putting together a PR...

**Comment by rkingon** [comment]
I've got some free time this next weekend, I'll get this integrated. Currently there is no regex that will allow  it to work since the QS is not parsed, only the pathname

**Comment by rkingon** [comment]
fixed in 975b3200eae4a56b877e93265f95aa0589f5045b per @mattweldon PR. thanks!
